# Generated by Django 6.1.1 on 2026-09-09 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('energy', 'Energy'), ('infrastructure', 'Infrastructure'), ('agriculture', 'Agriculture'), ('other', 'Other')], default='energy', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('flown', 'Flown'), ('delivered', 'Delivered')], default='requested', max_length=20)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('requested_date', models.DateField()),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='survey.client')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='survey.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('report', 'Report'), ('orthomosaic', 'Orthomosaic'), ('thermal', 'Thermal Imagery'), ('3d_model', '3D Model'), ('raw_footage', 'Raw Footage')], default='report', max_length=20)),
                ('delivered_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='survey.surveyproject')),
            ],
        ),
    ]
